apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: node-app-replica-set
  namespace: node-app
  labels:
    app: guestbook
    tier: node-label
spec:
  # modify replicas according to your case
  replicas: 10
  selector:
    matchLabels:
      tier: node-label
  template:
    metadata:
      namespace: node-app
      labels:
        tier: node-label
    spec:
      containers:
      - name: node-container-rep
        image: satish1137/node-app-batch-6
